//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPSema.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Customer
    {
        public int Id { get; set; }
        [DisplayName("Название Тура")]
        public string nameTour { get; set; }
        [DisplayName("Дата выезда")]
        public Nullable<System.DateTime> dateTour { get; set; }
        [DisplayName("Количество дней")]
        public string daysTour { get; set; }
        [DisplayName("Стоимость")]
        public Nullable<decimal> price { get; set; }
        [DisplayName("Транспорт")]
        public string transport { get; set; }
        [DisplayName("Проживание")]
        public string residence { get; set; }
        [DisplayName("Тип Тура")]
        public string typeTour { get; set; }
    }
}
